### ISSUE TITLE
How to export docx by gitbook?

### ISSUE THREAD

**Issue by chenweiyj** [GitbookIO/gitbook-convert#18]
I wrote my document in gitbook. However, some organization needs a word document. How can I generate .docx via gitbook?

**Comment by AaronO** [comment]
@chenweiyj `gitbook` doesn't support `.docx` export yet, it could be an interesting feature to implement in the future. Right now our team is busy working on other improvements and features, so I don't think we could implement it anytime soon.

However, pull requests are more than welcome :)

P.S: One approach that might work (not guaranteed) is to use gitbook to generate a single HTML file, which Word should then be able to import.
